#!/bin/sh
set -eu

version=$(cat VERSION)
msgfile=$1
tmp=$(mktemp)
awk -v stamp="$version" '!done && $0 !~ /^#/ { sub(/^v[0-9]+\.[0-9]+\.[0-9]+[+-][0-9][0-9][0-9][0-9][0-9][0-9][0-9a-zA-Z] /, ""); print stamp " " $0; done=1; next } { print }' "$msgfile" > "$tmp"
mv -f -- "$tmp" "$msgfile"