import { spawn } from 'node:child_process';
import { CredentialStore } from './credentials.js';

export interface BridgeResult { stdout: string; stderr: string; }
export type BridgeRunner = (file: string, args: string[], input: string) => Promise<BridgeResult>;
const bridge = "$request=[Console]::In.ReadToEnd()|ConvertFrom-Json;Add-Type @'\nusing System;using System.Runtime.InteropServices;public static class ModeradoCred{[StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]public struct C{public UInt32 Flags,Type;public string TargetName,Comment;public System.Runtime.InteropServices.ComTypes.FILETIME LastWritten;public UInt32 CredentialBlobSize;public IntPtr CredentialBlob;public UInt32 Persist,AttributeCount;public IntPtr Attributes;public string TargetAlias,UserName;}[DllImport(\"Advapi32.dll\",CharSet=CharSet.Unicode,SetLastError=true)]public static extern bool CredRead(string t,UInt32 y,UInt32 f,out IntPtr c);[DllImport(\"Advapi32.dll\",CharSet=CharSet.Unicode,SetLastError=true)]public static extern bool CredWrite(ref C c,UInt32 f);[DllImport(\"Advapi32.dll\",CharSet=CharSet.Unicode,SetLastError=true)]public static extern bool CredDelete(string t,UInt32 y,UInt32 f);[DllImport(\"Advapi32.dll\")]public static extern void CredFree(IntPtr b);}\n'@;try{if($request.operation -eq 'get'){$p=[IntPtr]::Zero;if(-not [ModeradoCred]::CredRead($request.reference,1,0,[ref]$p)){[Console]::Out.Write('{\"ok\":true}');exit 0};try{$c=[Runtime.InteropServices.Marshal]::PtrToStructure($p,[type][ModeradoCred+C]);$s=[Runtime.InteropServices.Marshal]::PtrToStringUni($c.CredentialBlob,[int]($c.CredentialBlobSize/2));[Console]::Out.Write((@{ok=$true;secret=$s}|ConvertTo-Json -Compress))}finally{[ModeradoCred]::CredFree($p)}}elseif($request.operation -eq 'set'){$b=[Text.Encoding]::Unicode.GetBytes($request.secret);$p=[Runtime.InteropServices.Marshal]::AllocHGlobal($b.Length);try{[Runtime.InteropServices.Marshal]::Copy($b,0,$p,$b.Length);$c=New-Object ModeradoCred+C;$c.Type=1;$c.TargetName=$request.reference;$c.CredentialBlobSize=$b.Length;$c.CredentialBlob=$p;$c.Persist=2;$c.UserName='Moderado';if(-not [ModeradoCred]::CredWrite([ref]$c,0)){throw 'write'};[Console]::Out.Write('{\"ok\":true}')}finally{[Runtime.InteropServices.Marshal]::FreeHGlobal($p)}}else{[void][ModeradoCred]::CredDelete($request.reference,1,0);[Console]::Out.Write('{\"ok\":true}')}}catch{[Console]::Error.Write('Credential Manager operation failed');exit 1}";
function encodedBridge(): string { return Buffer.from(bridge, 'utf16le').toString('base64'); }
const defaultRunner: BridgeRunner = (file, args, input) => new Promise((resolve, reject) => { const child = spawn(file, args, { shell: false, windowsHide: true, stdio: ['pipe', 'pipe', 'pipe'] }); let stdout = ''; let stderr = ''; child.stdout.on('data', (chunk: Buffer) => { stdout += chunk.toString(); }); child.stderr.on('data', (chunk: Buffer) => { stderr += chunk.toString(); }); child.on('error', reject); child.on('close', (code) => code === 0 ? resolve({ stdout, stderr }) : reject(new Error(stderr || `PowerShell exited with ${code}`))); child.stdin.end(input); });
export class WindowsCredentialStore implements CredentialStore { constructor(private readonly run: BridgeRunner = defaultRunner) {} async get(reference: string): Promise<string | undefined> { const parsed = JSON.parse(await this.invoke('get', reference)) as { secret?: unknown }; return typeof parsed.secret === 'string' ? parsed.secret : undefined; } async set(reference: string, secret: string): Promise<void> { await this.invoke('set', reference, secret); } async delete(reference: string): Promise<void> { await this.invoke('delete', reference); } private async invoke(operation: 'get' | 'set' | 'delete', reference: string, secret?: string): Promise<string> { try { const result = await this.run('powershell.exe', ['-NoProfile', '-NonInteractive', '-EncodedCommand', encodedBridge()], JSON.stringify({ operation, reference, secret })); if (!result.stdout.trim()) throw new Error(result.stderr); return result.stdout; } catch { throw new Error('Windows Credential Manager operation failed. Set the provider environment variable to continue.'); } } }

